[project]
name = "website"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.120.4",
    "jinja2>=3.1.6",
    "uvicorn>=0.38.0",
]
